id: d8c469daed524af480f3130807a66541
initial_creation_type: ocr
source_metadata:
  volumes:
    9be3ac1595dc446aa29bfb4b02f6b31e:
      base_file: v077.txt
      image_group_id: I1PD95923
      title: ''
      total_pages: 1254
      volume_number: 78
